### ISSUE TITLE
Null handling

### ISSUE THREAD

**Issue by klntsky** [jvliwanag/purescript-untagged-union#12]
There's some functionality for working with `undefined`, but not with Null. I ended up creating a custom foreign Null data type and defining it an instance of `HasRuntimeType`

Can we add a Null type here instead?

**Comment by jvliwanag** [comment]
Yup! Care to take a crack at it? There's a null type over at purescript-literals which this lib already depends on.

**Comment by klntsky** [comment]
Sure, I'll make a PR in a few days.
