### ISSUE TITLE
Add `HasRuntimeType` constraints for `|+|`

### ISSUE THREAD

**Issue by klntsky** [jvliwanag/purescript-untagged-union#15]
```
type OneOf' a b = HasRuntimeType a => HasRuntimeType b => OneOf a b
infixr 7 type OneOf' as |+|
```

Defining `|+|` as a synonym for `OneOf` does not enforce the constraints. It's meaningless to use `|+|` when we can't get the data out.

**Comment by klntsky** [comment]
I haven't checked the code above actually

**Comment by klntsky** [comment]
Seems like it's not going to work, at least that way.

Adding the constraint to `asOneOf` seems like a good idea though.

```
asOneOf :: forall a h t. HasRuntimeType a => Coercible a (OneOf h t) => a -> OneOf h t
asOneOf = coerce
```

**Comment by jvliwanag** [comment]
Sometimes describing a data type as `OneOf a b` is good enough even if you can't retrieve back whether it was `a` or `b` that you put in. This is especially true when simply passing arguments onto ffi libraries.
