### ISSUE TITLE
Polymorphic types are not easily coercible...

### ISSUE THREAD

**Issue by paluh** [jvliwanag/purescript-untagged-union#6]
I'm not sure if this can be handled without explicit type annotations. If this is the case we should probably provide a large warning in the docs ;-):

```purescript
type R = { x ∷ Maybe Int }

r ∷ R
r = OneOf.coerce { x: Nothing }
```

This fails with:

No type class instance was found for Untagged.Coercible.Coercible (Maybe t2) (Maybe Int) The instance head contains unknown type variables.
Consider adding a type annotation. while applying a function coerce of type Coercible t0 t1 => t0 -> t1 to argument { x: Nothing } while checking that expression coerce { x: Nothing } has type { x :: Maybe Int } in value declaration r where t1 is an unknown type t0 is an unknown type t2 is an unknown type

**Comment by paluh** [comment]
This is a minimal example:

```purescript
r ∷ Maybe Int
r = coerce Nothing
```

**Comment by paluh** [comment]
We can provide additional helper to build a mapping like:

```purescript
class CoercibleVia a b c | a b -> c
```
```purescript
coerceVia :: forall a b c. CoercibleVia a b c => Proxy b -> a -> c
```

And finish the instance chain with something like:

```purescript
...
else instance coerceOneOf :: (InOneOf a h t) => CoercibleVia a (OneOf h t) (OneOf h t)
else instance copyACoercibleVia :: CoercibleVia a b a
```

This seems to work but it is not as elegant as `coerce` and requires a `Proxy`. Maybe we can provide this fallback?

**Comment by paluh** [comment]
A really dirty prototype: https://try.purescript.org/?gist=196d67590e4eada43a89dcb18a4bdec2

**Comment by paluh** [comment]
But still case with polymorphic value in the `OneOf` chain causes a problem - if you please change value for the `y` to `Nothing` in the line 68 you can see that we are not able to pass this polymorphic type over and this case fails.

**Comment by paluh** [comment]
And one last remark which I'm able to make (it is 02:40 now, here - I hope there is some sens in it)  it seems that we are not able to nest `OneOf` inside itself (in `InOneOf` we are not able to do recursive `Coercible` check). On the other hand if we restrict ourselves to handling only optional fields (so providing only a wrapper like `UndefinedOr a`) we can probably have safe and arbitrarily nested records with coercing for optional fields.

**Comment by jvliwanag** [comment]
Yeah, having proper error messages is still on my todo list.

And the current restriction is that it cannot solve the types that it needs.

I'm not finding `coerceVia` appealing since:

```
r = OneOf.coerceVia (Proxy :: _ Int) { x: Nothing }
```

is longer than

```
r = OneOf.coerce { x: (Nothing :: _ Int) }
```

Other notes:

* I really wouldn't use this lib for non-ffi. :) So the `Maybe` case isn't that much of a concern
* What's concerning is the empty array `[]`. It can't solve what type it needs and you need to annotate it similarly: `[] :: _ Int`.
* For nested use cases, I normally auto gen helpers as well:

```
type Foo =
  { children: Undefined |+| FooChild |+| Array FooChild
  }

foo :: forall r. Coercible r Foo => r -> Foo
foo = coerce

type FooChild = String |+| Number

fooChild :: forall r. Coercible r FooChild => r -> FooChild
fooChild = coerce

x = foo {}
x1 = foo { children: fooChild "bar" }
x2 = foo { children: [ fooChild 8.0 ] }
```

The only confusing case is:

```
x3 = foo { children: ([] :: _ FooChild) }
```

**Comment by paluh** [comment]
> r = OneOf.coerceVia (Proxy :: _ Int) { x: Nothing }
> is longer than
> r = OneOf.coerce { x: (Nothing :: _ Int) }

Please note that `coerceVia (Proxy :: Proxy Props)` can be provided by the library function which consumes data so the burden of this annotation would be on the library author (in the case of internal PS usage) or on a codegen.

> So the Maybe case isn't that much of a concern

It is one point of view. If you want to use this library just in PS for handling optional fields `Maybe` and any other polymorphic type would be a concern.

**Comment by paluh** [comment]
So maybe you are right that this library can be dedicated mainly for a codegen use cases.

Probably a similar one with only `UndefinedOr a` which handles also an arbitrary nesting of optional records could be provided to handle efficiently optional fields on the PS side. This second library should somehow enable solving this issues with polymorphic values I think (be it with `coerceVia` as an extra helper or anything else).

**Comment by paluh** [comment]
I propose to name this lib for optional property handling via first class `undefined` + record coercing: _purescript-undefined-is-not-a-problem_ :-P

Do you want to provide a repo for it or should I start a new one on the _codegen_ org? Do you think that this narrow scenario is a good fit for our org too?

**Comment by paluh** [comment]
@jvliwanag I've created a stub for a lib which is solely based on your untagged union idea but used only for optional fields:

https://github.com/paluh/purescript-undefined-is-not-a-problem

I hope that it is not a problem that I've created this clone for now. I'm really open to merge it somehow or move it to the codegen org when I finish it. Please let me know what do you think.

**Comment by paluh** [comment]
To be honest I wasn't able to fully solve this problem even in a simpler setting of my derived library.
I've fallen back to your signature and dropped typelevel function ;-)

I'm closing this for now
